user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

user_route_plus:
    resource: "@UserBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /maison-editions


